"""
mt_flag.py — check 5 (§7.5): the multiple-testing flag. Deterministic; zero LLM.

NOT a lattice toggle (registry D7, D-A13): multiple testing is a property of
inference over the family of strategies tried during the audited paper's
DISCOVERY process, not of any single run — there is no per-strategy on/off pair,
so this check is computed outside the lattice and is **informational: it never
gates routing** (A7/D7). Three registered flag conditions (design §7.5, constants
pre-registered under ``auditor.mt_flag`` in docs/thresholds.yaml):

  1. the paper's t-statistic sits in the just-significant band — |t| within
     ``t_band`` (INCLUSIVE bounds; |t| so a negative-premium factor's -2.2 is
     equally just-significant; boundary ties flag, the conservative direction
     for an informational marker);
  2. MORE than ``max_free_parameters`` free parameters in the variable
     construction;
  3. exact name match against the Dickerson zoo label set (D5, RESOLVED
     2026-09-03: data/dickerson_zoo/names.csv, generated by
     scripts/build_dickerson_names.py from the pulled zoo's 108 column headers;
     both sides casefold+strip at compare time — the labels were lowercased at
     ingest, candidates may not be).

A condition whose input is absent is NOT_EVALUATED — reported as such, never
silently false (an unevaluated condition is missing evidence, not evidence of
absence). ``flag`` is true iff ANY evaluated condition is met. The RQ3
``counted_as_failure`` accounting reports BOTH interpretations downstream; this
module only states the conditions.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


class ZooNamesError(ValueError):
    """The zoo label file is missing/empty — fail loud, never silently no-match."""


def load_zoo_names(path: str | Path, *, strip_trailing_asterisk: bool = False) -> frozenset[str]:
    """The Dickerson label set, casefolded, from the generated names.csv
    (comment lines ``#`` and the ``name`` header skipped).

    ``strip_trailing_asterisk`` applies the registered 2026-09-03
    normalisation: the source table decorates some labels with a trailing ``*``
    footnote marker (``str*``, ``mom9_1*``); stripping it is pure orthography,
    never a semantic identification (those go through the registered alias
    table instead)."""
    p = Path(path)
    if not p.exists():
        raise ZooNamesError(
            f"zoo names file not found: {p} — regenerate with "
            "scripts/build_dickerson_names.py (machine-local, under /data/)")
    names = [
        line.strip().casefold()
        for line in p.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith("#") and line.strip() != "name"
    ]
    if strip_trailing_asterisk:
        names = [n.rstrip("*") for n in names]
    if not names:
        raise ZooNamesError(f"zoo names file is empty: {p}")
    return frozenset(names)


@dataclass(frozen=True)
class MtCondition:
    evaluated: bool
    met: bool | None            # None iff not evaluated
    detail: str

    def to_dict(self) -> dict:
        return {"evaluated": self.evaluated, "met": self.met, "detail": self.detail}


@dataclass(frozen=True)
class MtFlagResult:
    strategy_label: str
    t_band: MtCondition
    free_parameters: MtCondition
    zoo_name_match: MtCondition
    flag: bool                  # any EVALUATED condition met; informational only

    def to_dict(self) -> dict:
        return {
            "check": "mt_flag",
            "informational": True,       # never gates routing (A7/D7)
            "strategy_label": self.strategy_label,
            "conditions": {
                "t_band": self.t_band.to_dict(),
                "free_parameters": self.free_parameters.to_dict(),
                "zoo_name_match": self.zoo_name_match.to_dict(),
            },
            "flag": self.flag,
        }


def compute_mt_flag(
    strategy_label: str,
    *,
    t_stat: float | None,
    free_parameters: int | None,
    zoo_names: frozenset[str] | None,
    t_band: tuple[float, float],
    max_free_parameters: int,
    aliases: dict[str, str] | None = None,
) -> MtFlagResult:
    """Evaluate the three §7.5 conditions from EXPLICIT inputs (the caller states
    its sources; nothing is fetched here). ``None`` input -> NOT_EVALUATED."""
    lo, hi = float(t_band[0]), float(t_band[1])
    if not lo < hi:
        raise ValueError(f"t_band must be (lo, hi) with lo < hi; got {t_band}")

    if t_stat is None:
        band = MtCondition(False, None, "t-stat not supplied")
    else:
        met = lo <= abs(float(t_stat)) <= hi
        band = MtCondition(True, met,
                           f"|t|={abs(float(t_stat)):.3f} vs band [{lo}, {hi}] (inclusive)")

    if free_parameters is None:
        free = MtCondition(False, None, "free-parameter count not supplied")
    else:
        n = int(free_parameters)
        if n < 0:
            raise ValueError(f"free_parameters must be >= 0; got {free_parameters}")
        free = MtCondition(True, n > max_free_parameters,
                           f"{n} free parameter(s) vs max {max_free_parameters}")

    if zoo_names is None:
        zoo = MtCondition(False, None, "zoo names not supplied")
    else:
        candidate = strategy_label.strip().casefold()
        alias = (aliases or {}).get(candidate)
        if candidate in zoo_names:
            zoo = MtCondition(True, True,
                              f"{candidate!r} IS in the {len(zoo_names)}-label "
                              "Dickerson zoo (direct)")
        elif alias is not None and alias.strip().casefold() in zoo_names:
            zoo = MtCondition(True, True,
                              f"{candidate!r} IS in the zoo via the registered "
                              f"alias {alias!r}")
        else:
            zoo = MtCondition(True, False,
                              f"{candidate!r} is not in the {len(zoo_names)}-label "
                              "Dickerson zoo (no direct or aliased match)")

    flag = any(c.met for c in (band, free, zoo) if c.evaluated)
    return MtFlagResult(strategy_label=strategy_label, t_band=band,
                        free_parameters=free, zoo_name_match=zoo, flag=flag)
