"""P1 paper arm — pair the paper arm's scored cells with the field-key arm's, per basis.

Reads, never re-runs:
  * field-key arm: results/consistent_basis/<basis>/codegen/p1_results_reported.json
  * paper arm:     results/codegen_paper_arm/<basis>/p1_paper_results_reported.json

Writes ``comparison.json`` and ``comparison.md`` beside the paper-arm record, plus a top-level
``README.md`` indexing both bases. Every number comes from the two records via
``evaluation.codegen.paper_arm.compare_arms``.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
for _p in (str(_REPO_ROOT), str(_REPO_ROOT / "scripts")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from evaluation.codegen.jsonio import dump_json  # noqa: E402
from evaluation.codegen.paper_arm import compare_arms, render_comparison_md  # noqa: E402
from scripts import basis_inputs  # noqa: E402
from scripts.run_p1_paper_codegen import FIELD_KEY_RECORD, OUT_ROOT  # noqa: E402


def build(basis: str, out_root: Path = OUT_ROOT, phase: str = "reported") -> dict:
    field_key_path = basis_inputs.basis_dir(basis, "codegen") / FIELD_KEY_RECORD
    paper_path = Path(out_root) / basis / f"p1_paper_results_{phase}.json"
    for path in (field_key_path, paper_path):
        if not path.exists():
            raise FileNotFoundError(f"record missing: {path}")
    field_key = json.loads(field_key_path.read_text(encoding="utf-8"))
    paper = json.loads(paper_path.read_text(encoding="utf-8"))
    comparison = compare_arms(field_key, paper)
    comparison["sources"] = {"field_key": str(field_key_path.relative_to(_REPO_ROOT)),
                             "paper": str(paper_path.relative_to(_REPO_ROOT))}
    comparison["paper_reportable"] = paper.get("reportable")
    comparison["paper_reportable_blockers"] = paper.get("reportable_blockers")
    out = paper_path.parent
    (out / "comparison.json").write_text(dump_json(comparison), encoding="utf-8")
    (out / "comparison.md").write_text(render_comparison_md(comparison, basis=basis), encoding="utf-8")
    return comparison


def render_readme(comparisons: dict[str, dict]) -> str:
    lines = [
        "# P1 paper arm",
        "",
        "Paper → executable strategy with no specification in between: the P1 code-generation "
        "experiment with the paper's frozen canonical text in place of the field-key. Generated by "
        "`scripts/build_paper_arm_report.py`; do not hand-edit.",
        "",
        "| Basis | Arm | RUNS_RIGHT | RUNS_WRONG | WONT_RUN | NO_DATUM | Reportable |",
        "|---|---|---|---|---|---|---|",
    ]
    for basis, comp in comparisons.items():
        for arm in ("field_key", "paper"):
            c = comp["counts_all_10"][arm]
            rep = comp["paper_reportable"] if arm == "paper" else "see field-key record"
            lines.append(f"| {basis} | {arm} | {c['RUNS_RIGHT']} | {c['RUNS_WRONG']} | "
                         f"{c['WONT_RUN']} | {c['NO_DATUM']} | {rep} |")
    lines += ["", "Per-basis detail: `<basis>/comparison.md`."]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--basis", choices=basis_inputs.BASES, action="append",
                    help="repeatable; default both bases")
    ap.add_argument("--out-root", default=str(OUT_ROOT))
    args = ap.parse_args(argv)
    comparisons = {b: build(b, Path(args.out_root)) for b in (args.basis or basis_inputs.BASES)}
    (Path(args.out_root) / "README.md").write_text(render_readme(comparisons), encoding="utf-8")
    for basis, comp in comparisons.items():
        print(f"{basis}: all 10 {comp['counts_all_10']}; transitions {comp['transitions']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
