#!/usr/bin/env python
"""extension_1 — the pre-committed human-authored baseline arm, run on the development window.

`docs/extension_1_config.yaml` registers BAA-AAA credit-cycle regime conditioning of the
corrected parent under the `binary_above_historical_median` interaction, with the split
threshold FROZEN at the committed development median (0.935 pp) so no threshold is chosen on
performance. This driver runs exactly that one hypothesis through the same gate stack the
generated proposals face, and reports whatever the gates say.

Three properties the registration fixes, and this driver honours:

  * **standalone, never a family** — `extension_1_standalone` is a single hypothesis, so it is
    run alone (m = 1) and its p-value is never pooled into a proposal family's BH-FDR;
  * **not generated by the procedure under test** — its provenance is
    `ProposalSource.PRE_COMMITTED_HUMAN`, not a ladder rung;
  * **development window only** — the protected window is not touched here under any flag.

    ./.venv/bin/python scripts/run_extension_1.py --basis clean
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import date
from pathlib import Path

import yaml

_REPO_ROOT = Path(__file__).resolve().parents[1]
for _p in (str(_REPO_ROOT), str(_REPO_ROOT / "scripts")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from agents.scientist.experimentalist.orchestrator import run_experimentalist  # noqa: E402
from agents.scientist.researcher.library import (  # noqa: E402
    available_conditioning_variables,
    load_library,
)
from agents.scientist.schemas.proposal import (  # noqa: E402
    ConfigDelta,
    ExtensionProposal,
    Generation,
    ProposalSource,
)
from evaluation.codegen.jsonio import dump_json  # noqa: E402
from run_rq4_funnel import (  # noqa: E402
    bbw4_frame,
    build_case,
    corrected_str_parent,
    crowding_config_for,
    load_macro_series,
    repo_relative,
    resolve_funnel_paths,
)
from scripts import basis_inputs  # noqa: E402

from agents.scientist.experimentalist.audit_checks import load_reporting_delays  # noqa: E402
from shared.evaluation.crowding import load_crowding_factor_bundle  # noqa: E402

RUN_DATE = date.today().isoformat()
_CONFIG = _REPO_ROOT / "docs" / "extension_1_config.yaml"

#: mech_003 "Conditional recovery of the credit risk premium" — the registered claim that
#: conditioning on the CREDIT-market regime recovers premium an unconditional sort leaves. That
#: is extension_1's own rationale, and BAA-AAA is a credit spread; the mechanism is chosen to
#: match the registration, not to clear a gate.
MECHANISM_REF = "mech_003"
TEMPLATE_REF = "lagged_binary_regime_interaction_v1"


def load_config(path: Path | None = None) -> dict:
    """The registration itself — the frozen median and its window live here, never in code."""
    return yaml.safe_load((path or _CONFIG).read_text(encoding="utf-8"))


def pre_registered(path: Path | None = None) -> tuple[bool, str]:
    """The registration status lives in the config's header comment (the file is the registration).
    Refuse to run a DRAFT: a threshold that is not pre-registered is not a pre-commitment."""
    text = (path or _CONFIG).read_text(encoding="utf-8")
    if "STATUS: PRE-REGISTERED" in text:
        return True, "STATUS: PRE-REGISTERED"
    if "STATUS: DRAFT" in text:
        return False, "STATUS: DRAFT — not final"
    return False, "no STATUS line found"


def build_extension_1(case, cfg: dict) -> ExtensionProposal:
    """The registered hypothesis as a proposal the gate stack can execute."""
    median = cfg["median_split"]["median_baa_aaa_spread_pp"]
    lag_ref = cfg.get("lag_months_ref", "reporting_delays.baa_aaa_spread.lag_months")
    return ExtensionProposal(
        proposal_id="extension_1",
        case_id=case.case_id,
        parent_strategy_id=case.strategy_id,
        mechanism_ref=MECHANISM_REF,
        template_ref=TEMPLATE_REF,
        rationale=(
            "Pre-committed baseline arm (docs/extension_1_config.yaml): condition the corrected "
            "parent on the BAA-AAA credit-cycle regime, split at the FROZEN development median "
            f"of {median} pp so the threshold is never chosen on performance."),
        config_delta=ConfigDelta(
            conditioning_variable="baa_aaa_spread",
            conditioning_lag_months=1,          # BAA-AAA is never used at lag 0 (lag_months_ref)
            interaction_form="binary_above_historical_median",
        ),
        prediction=(
            "The corrected parent's premium is larger in the high-spread (above-median) state "
            "than in the low-spread state."),
        required_inputs=("baa_aaa_spread",),
        generation=Generation(
            source=ProposalSource.PRE_COMMITTED_HUMAN,
            seed=0,
            model="human_authored",
            prompt_version="extension_1_config_v1.0.0",
            library_version=f"lag_months_ref={lag_ref}",
            generated_at="2026-08-07T00:00:00Z",   # the registration date, not the run date
        ),
    )


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--basis", choices=basis_inputs.BASES, default="clean")
    args = ap.parse_args(argv)

    ok, status = pre_registered()
    if not ok:
        print(f"REFUSED: docs/extension_1_config.yaml is not pre-registered ({status}). "
              "A threshold that is not pre-registered is not a pre-commitment.", file=sys.stderr)
        return 2

    cfg = load_config()
    paths = resolve_funnel_paths(args.basis)
    case, params = build_case(paths["audit"],
                              corrected_run_ref=repo_relative(paths["audit"].parent))
    if not case.failed_check_ids:
        print("REFUSED: the parent did not enter — extension_1 extends a corrected parent that "
              "RQ3 entry selected, and there is none.", file=sys.stderr)
        return 2

    library = load_library()
    available = available_conditioning_variables()
    panel, base_rulebook, parent_returns, direction = corrected_str_parent(args.basis)
    macros = load_macro_series(panel["date"].min(), panel["date"].max())
    bbw4 = bbw4_frame(paths["factors_dir"])
    crowding_cfg = crowding_config_for(paths["factors_dir"])

    proposal = build_extension_1(case, cfg)
    report = run_experimentalist(
        case, [proposal], library, panel=panel, base_rulebook=base_rulebook,
        bbw4_factors=bbw4, holding_period=1, signal_lookback=1, available_variables=available,
        macros=macros,
        m=1,                                   # standalone hypothesis: never a family
        q=params.q, cap=None, direction=direction,
        crowding_config=crowding_cfg,
        crowding_factors=load_crowding_factor_bundle(crowding_cfg),
        reporting_delays=load_reporting_delays())

    record = next((r for r in report.records if r.proposal_id == "extension_1"), None)
    if record is None:
        print("REFUSED: the gate stack returned no record for extension_1.", file=sys.stderr)
        return 2

    refusal = getattr(record, "refusal_code", None)
    result = {
        "experiment": "extension_1_standalone",
        "computed_after_the_fact": True,
        "computed_on": RUN_DATE,
        "registration": {
            "config": repo_relative(_CONFIG),
            "status": status,
            "frozen_median_pp": cfg["median_split"]["median_baa_aaa_spread_pp"],
            "median_window": cfg["median_split"]["window"],
            "sensitivity_median_pp": (cfg["median_split"]
                                      .get("sensitivity_primary_inference_window", {})
                                      .get("median_baa_aaa_spread_pp")),
        },
        "family": ("standalone single hypothesis — NOT pooled into any proposal family's BH-FDR "
                   "(scientist_protocol: extension_1_standalone)"),
        "window": "development only; the protected window is untouched",
        "basis": args.basis,
        "inputs": {"audit_report": repo_relative(paths["audit"]),
                   "factors_dir": repo_relative(paths["factors_dir"])},
        "parent": {"strategy_id": case.strategy_id, "direction": direction,
                   "corrected_parent_mean_per_month": float(parent_returns.mean())},
        "proposal": json.loads(proposal.model_dump_json()),
        "outcome": {
            "refusal_code": (refusal.value if refusal is not None else None),
            "booleans": (record.booleans.to_dict() if hasattr(record.booleans, "to_dict")
                         else dict(record.booleans or {})),
            "measurements": (record.measurements.to_dict()
                             if getattr(record, "measurements", None) is not None else None),
            "advanced": "extension_1" in tuple(report.advanced),
        },
        "funnel": dict(report.funnel) if report.funnel else {},
    }

    out_dir = basis_inputs.basis_dir(args.basis, "rq4", "extension_1")
    out_dir.mkdir(parents=True, exist_ok=True)
    out_json = out_dir / "extension_1.json"
    if out_json.exists():
        print(f"REFUSED: {out_json} already exists; move or delete it to re-run.", file=sys.stderr)
        return 2
    out_json.write_text(dump_json(result), encoding="utf-8")

    print(f"extension_1 ({args.basis}): refusal={result['outcome']['refusal_code']} "
          f"advanced={result['outcome']['advanced']}")
    print(f"  frozen median {result['registration']['frozen_median_pp']} pp "
          f"({result['registration']['status']})")
    meas = result["outcome"]["measurements"] or {}
    if meas.get("gross"):
        print(f"  gross: {json.dumps(meas['gross'])[:200]}")
    print(f"results written: {out_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
