"""
G3 gold calibration -- the scoring unit (build brief §8 G3, D34, D37).

The golden end-to-end assertions, and the trap guards. Every trap test is
BEHAVIOURAL on real committed artefacts rather than a source grep: a grep passes
if someone renames a symbol, whereas asserting that two quantities genuinely
differ on real data fails the moment a "simplification" collapses them.

Run artefacts live under runs/ (gitignored, regenerated by
scripts/run_librarian.py), so the real-data tests skip when absent rather than
failing a fresh clone -- the same pattern test_g2_round_trip.py uses for an
anchor gated on a canonical-text freeze.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import pytest  # noqa: E402

from evaluation.harness.compare_policy import Comparability, compare_field  # noqa: E402
from evaluation.harness.field_pairing import FieldKey  # noqa: E402
from evaluation.harness.gold_calibration import (  # noqa: E402
    EXCLUDED_OUTCOMES,
    SHIPPED_OUTCOMES,
    Outcome,
    score_anchor,
)
from evaluation.harness.run_artefacts import (  # noqa: E402
    ArtefactIntegrityError,
    RunField,
    load_run,
)

_ROOT = Path(__file__).resolve().parents[2]
_BBW = _ROOT / "runs" / "g3_v3" / "bbw"
_JNPS = _ROOT / "runs" / "g3_v3" / "jnps"

_needs_bbw = pytest.mark.skipif(
    not (_BBW / "trace_0.json").exists(),
    reason="post-fix BBW dev run absent (runs/ is gitignored); regenerate with run_librarian.py",
)
_needs_jnps = pytest.mark.skipif(
    not (_JNPS / "trace_0.json").exists(),
    reason="post-fix JNPS dev run absent (runs/ is gitignored); regenerate with run_librarian.py",
)
_DRR = _ROOT / "runs" / "g3_v3" / "drr"
_needs_str = pytest.mark.skipif(
    not (_DRR / "trace_0.json").exists(),
    reason="DRR dev run absent (runs/ is gitignored); regenerate with run_librarian.py",
)


# --- golden end-to-end -------------------------------------------------------

@_needs_bbw
def test_g3_drf_golden_counts():
    """The G3 analogue of test_g2_drf_byte_equal: pin the whole outcome vector."""
    s = score_anchor("drf", _BBW)
    c = s.counts()
    assert len(s.rows) == 47
    assert c[Outcome.SHIPPED_CORRECT] == 3
    assert c[Outcome.SHIPPED_WRONG] == 1
    assert c[Outcome.SHIPPED_GOLD_SILENT] == 0
    assert c[Outcome.SHIPPED_NOT_SCORABLE] == 0
    assert c[Outcome.ABSTAINED_GOLD_STATED] == 14
    assert c[Outcome.ABSTAINED_GOLD_SILENT] == 26
    assert c[Outcome.NOT_ASKED] == 0
    assert c[Outcome.EXCLUDED_WEAKER_RUBRIC] == 2
    assert c[Outcome.EXCLUDED_NOT_FIELD_EXTRACTED] == 1
    assert sum(c.values()) == 47


@_needs_jnps
def test_g3_mom6_golden_counts():
    s = score_anchor("mom6", _JNPS)
    c = s.counts()
    assert len(s.rows) == 47
    assert c[Outcome.SHIPPED_CORRECT] == 6
    assert c[Outcome.SHIPPED_WRONG] == 0
    assert c[Outcome.SHIPPED_GOLD_SILENT] == 1
    assert c[Outcome.ABSTAINED_GOLD_STATED] == 15
    assert c[Outcome.ABSTAINED_GOLD_SILENT] == 22
    assert sum(c.values()) == 47


@_needs_bbw
def test_g3_a_wrong_shipped_value_is_scored_wrong():
    """drf ships sample_start = 2002-07 where the gold says 2004-07 -- the models
    read the TRACE data-availability date instead of the portfolio sample start.
    A genuine correlated error (both models agreed), correctly caught."""
    s = score_anchor("drf", _BBW)
    row = next(r for r in s.rows if r.key.name == "sample_start")
    assert row.outcome is Outcome.SHIPPED_WRONG
    assert row.gold_value == "2004-07"
    assert row.run_value == "2002-07"


@_needs_str
def test_g3_absent_control_axis_scores_the_run_as_over_claiming():
    """str is a SINGLE sort: the gold has no control axis at all, so
    _iter_inherited yields no path for it. The pairing injects an explicit None
    comparand, which is what makes the run's assertion of a control axis --
    naming the sort signal itself -- visible as a fabrication rather than
    silently dropped."""
    s = score_anchor("str", _DRR)
    row = next(r for r in s.rows if r.key.name == "control_axis")
    assert row.outcome is Outcome.SHIPPED_GOLD_SILENT
    assert row.gold_value is None
    assert row.run_value == "prior_1m_excess_return"


@_needs_str
def test_g3_str_golden_counts():
    """The third anchor, extractable for the first time after the D39 prompt nudge
    and the D40 ladder fix."""
    s = score_anchor("str", _DRR)
    c = s.counts()
    assert len(s.rows) == 47
    assert c[Outcome.SHIPPED_CORRECT] == 6
    assert c[Outcome.SHIPPED_WRONG] == 1
    assert c[Outcome.SHIPPED_GOLD_SILENT] == 1
    assert c[Outcome.ABSTAINED_GOLD_STATED] == 14
    assert sum(c.values()) == 47


@_needs_str
def test_g3_composite_metric_matches_gold_exactly():
    """str is the anchor whose headline number is DRR's famous -0.99. The
    paper_metric field type reproduces the full {mean, t_stat, unit} triple."""
    s = score_anchor("str", _DRR)
    row = next(r for r in s.rows if r.key.name == "claimed_headline_metric")
    assert row.outcome is Outcome.SHIPPED_CORRECT
    assert row.gold_value["mean"] == -0.99


@_needs_bbw
def test_g3_correct_signal_is_not_scored_as_a_fabrication():
    """Regression: _iter_inherited walks INTO a SignalRef and yields the bare
    concept_id, so the gold side of compare_signal is a string, not a SignalRef.
    Treating a bare string as "no signal" scored every correct sort_signal as a
    fabrication."""
    s = score_anchor("drf", _BBW)
    row = next(r for r in s.rows if r.key.name == "sort_signal")
    assert row.outcome is Outcome.SHIPPED_CORRECT
    assert row.gold_value == row.run_value == "var_5pct"


@_needs_bbw
def test_g3_universe_filter_is_excluded_not_counted_as_a_reader_failure():
    """D37 ruling 7: prose is rubric territory and no rubric is authored. It must
    not land in the missed-evidence set, where it would inflate the §3.6 rate
    that decides the ReAct-vs-k=3 question."""
    s = score_anchor("drf", _BBW)
    row = next(r for r in s.rows if r.key.name == "universe_filter")
    assert row.outcome is Outcome.EXCLUDED_WEAKER_RUBRIC
    assert not row.is_missed_evidence


@_needs_bbw
def test_g3_strategy_label_excluded_but_counted():
    """D37 ruling 4. Counted, not dropped -- an exclusion leaving no trace in the
    totals is indistinguishable from a field nobody thought about."""
    s = score_anchor("drf", _BBW)
    rows = s.by_outcome(Outcome.EXCLUDED_NOT_FIELD_EXTRACTED)
    assert len(rows) == 1
    assert rows[0].dotted_path == "header.strategy_label"


# --- trap guards -------------------------------------------------------------

def test_g3_runfield_does_not_expose_the_agreement_bit():
    """form_filler sets trace agreement to (tag == "STATED"), which is NOT model
    concord. RunField must not carry it at all."""
    import dataclasses

    names = {f.name for f in dataclasses.fields(RunField)}
    assert "agreement" not in names
    assert "models_agree" in {p for p in dir(RunField)}


@_needs_bbw
def test_g3_models_agree_genuinely_differs_from_the_trace_bit():
    """The behavioural half of the guard. On the real BBW run there are fields
    where both models agreed but the quote gate failed: the trace bit says False
    while true concord is True. If anyone "simplifies" the scorer back to reading
    trace["agreement"], this fails."""
    import json

    art = load_run(_BBW)
    raw = {r["field"]: r for r in json.loads((_BBW / "trace_0.json").read_text())["records"]}
    divergent = [name for name, f in art.fields.items() if raw[name]["agreement"] != f.models_agree]
    assert divergent, "expected at least one field where the trace bit != true agreement"
    # and at least one of them is the agree-but-gate-failed population
    assert any("agree_quote_gate_failed" in art.fields[n].conditions for n in divergent)


@_needs_bbw
def test_g3_conditions_are_incidence_not_a_partition():
    """The ordered D9 merge attributes each field to ONE reason (quote gate before
    single-response), so the shipped reason under-counts one-model-mute fields.
    conditions is the order-free view; the two must genuinely disagree, or the
    metrics layer would be reporting one number twice."""
    art = load_run(_BBW)
    one_silent = sum(1 for f in art.fields.values() if "one_silent" in f.conditions)
    labelled = sum(1 for f in art.fields.values() if f.shipped_reason == "single_response")
    assert one_silent > labelled


@_needs_bbw
def test_g3_trace_integrity_is_verified_on_load():
    """load_run proves dict traversal read exactly the bytes the spec header
    hashed (D12). Corrupting the trace must be caught."""
    import copy
    import json

    from evaluation.harness.run_artefacts import verify_trace_integrity

    spec = json.loads((_BBW / "spec_0.json").read_text())
    trace = json.loads((_BBW / "trace_0.json").read_text())
    verify_trace_integrity(trace, spec)          # the real pair verifies
    tampered = copy.deepcopy(trace)
    tampered["records"][0]["final_tag"] = "STATED"
    with pytest.raises(ArtefactIntegrityError):
        verify_trace_integrity(tampered, spec)


def test_g3_append_corrupted_run_is_refused():
    """runs/bbw_full. (a trailing-dot typo dir) was written twice: _archive
    appends while the spec is overwritten, so its raw archive has more lines than
    the trace has records. Scoring it would mix calls from different runs."""
    corrupt = _ROOT / "runs" / "bbw_full."
    if not (corrupt / "trace_0.json").exists():
        pytest.skip("the corrupted fixture directory is not present")
    with pytest.raises(ArtefactIntegrityError):
        load_run(corrupt)


# --- compare policy ----------------------------------------------------------

def test_g3_unnormalisable_gold_is_not_scorable_rather_than_wrong():
    """D37 ruling 2: gold hac_lags = "floor(T^0.25)" is a faithful transcription
    into a field type that cannot hold it. Neither correct nor wrong."""
    out = compare_field(FieldKey("hac_lags"), "floor(T^0.25)", 4)
    assert out.comparability is Comparability.GOLD_UNNORMALISABLE
    assert out.equal is None
    # the wrapper is what protects us -- normalise itself still raises
    from agents.librarian.errors import LibrarianSchemaError
    from agents.librarian.pipeline.form_filler import normalise

    with pytest.raises(LibrarianSchemaError):
        normalise("hac_lags", "floor(T^0.25)")


def test_g3_all_four_none_vs_signal_cells():
    class _Concept:
        def __init__(self, v): self.value = v

    class _Sig:
        def __init__(self, v):
            self.concept_id = _Concept(v)
            self.parameters = {}

    k = FieldKey("control_axis")
    assert compare_field(k, None, None).equal is True
    assert compare_field(k, None, "var_5pct").equal is False        # fabrication
    assert compare_field(k, _Sig("credit_rating"), None).equal is False
    assert compare_field(k, _Sig("credit_rating"), "credit_rating").equal is True
    assert compare_field(k, _Sig("credit_rating"), "var_5pct").equal is False


def test_g3_prose_fields_have_no_policy():
    for name in ("method_summary", "universe_filter"):
        out = compare_field(FieldKey(name), "some gold prose", "some run prose")
        assert out.comparability is Comparability.NO_POLICY
        assert out.equal is None


def test_g3_paper_metric_compares_as_a_mapping():
    m = {"mean": 0.7, "t_stat": 3.6, "unit": "pct_per_month"}
    assert compare_field(FieldKey("claimed_headline_metric"), m, dict(m)).equal is True
    assert compare_field(FieldKey("claimed_headline_metric"), m,
                         {"mean": 0.7, "t_stat": 3.9, "unit": "pct_per_month"}).equal is False


def test_g3_parameterised_gold_concept_is_declared_not_scorable():
    """D34 wants concept + canonical parameters. The run's parameters live in
    separate trace records and are not joined yet, so a parameterised gold
    concept must NOT be scored on concept alone -- that would report a match
    nothing checked."""
    class _Concept:
        def __init__(self, v): self.value = v

    class _Sig:
        def __init__(self, v, p):
            self.concept_id = _Concept(v)
            self.parameters = p

    out = compare_field(FieldKey("sort_signal"), _Sig("var_5pct", {"window": 36}), "var_5pct")
    assert out.comparability is Comparability.NO_POLICY
    assert out.equal is None


# --- denominators ------------------------------------------------------------

@_needs_bbw
def test_g3_not_asked_is_in_coverage_but_out_of_missed_evidence():
    """D37 ruling 3, the asymmetry. Asserted on a synthetic row rather than the
    real run, which currently has no NOT_ASKED field."""
    s = score_anchor("drf", _BBW)
    headline = [r for r in s.rows if r.outcome not in EXCLUDED_OUTCOMES]
    shipped = [r for r in headline if r.outcome in SHIPPED_OUTCOMES]
    assert len(shipped) == 4 and len(headline) == 44        # coverage 4/44
    # NOT_ASKED never counts as missed evidence
    assert all(not r.is_missed_evidence for r in s.rows if r.outcome is Outcome.NOT_ASKED)


# --- multi-construction archive integrity (2026-09-03) -----------------------

_BBW4 = _ROOT / "runs" / "bbw_4anchor_report"
_needs_bbw4 = pytest.mark.skipif(
    not (_BBW4 / "trace_2.json").exists(),
    reason="extended 3-construction BBW run absent (runs/ is gitignored)",
)


@_needs_bbw4
def test_multi_construction_archive_sums_across_traces():
    """A legitimate multi-construction dir (extended BBW enum: DRF+CRF+LRF) holds
    every construction's calls in ONE archive; the integrity guard must compare
    against the SUM of all traces, not the single loaded trace (2026-09-03 fix:
    the old per-trace comparison false-positived on exactly this layout)."""
    for i in range(3):
        load_run(_BBW4, strategy_index=i)              # must not raise


@_needs_bbw4
def test_multi_construction_double_write_still_refused(tmp_path):
    """The guard's real target -- a dir written twice -- still trips at 2x the sum."""
    import shutil

    d = tmp_path / "bbw4"
    shutil.copytree(_BBW4, d)
    for p in (d / "raw").glob("raw_model_*.jsonl"):
        p.write_text(p.read_text() * 2, encoding="utf-8")
    with pytest.raises(ArtefactIntegrityError):
        load_run(d, strategy_index=0)


@_needs_bbw4
def test_stray_trace_named_file_does_not_join_the_sum(tmp_path):
    """Review hardening (2026-09-04): only int-suffixed traces enter the
    integrity sum -- a stray trace_backup.json must not mask a double-write."""
    import shutil

    d = tmp_path / "bbw4"
    shutil.copytree(_BBW4, d)
    (d / "trace_backup.json").write_text('{"records": [1, 2, 3]}', encoding="utf-8")
    load_run(d, strategy_index=0)                      # must not raise
